interface Event {
    id: number;
    name: string;
    description: string;
    location: string;
    date: string;
    category: string;
    time: string;
    availableSeats: number;
    price: number;
    isFree: boolean;
  }
  
  export const events: Event[] = [
    {
      id: 1,
      name: 'Concert in the Park',
      description: 'A relaxing evening with classical music.',
      location: 'New York',
      date: '2024-08-10',
      category: 'Music',
      time: '18:00:00',
      availableSeats: 150,
      price: 100000,
      isFree: false,
    },
    {
      id: 2,
      name: 'Art Exhibition',
      description: 'Explore the latest art from local artists.',
      location: 'Art Gallery',
      date: '2024-08-12',
      category: 'Art',
      time: '10:00:00',
      availableSeats: 50,
      price: 50000,
      isFree: false,
    },
    {
      id: 3,
      name: 'Tech Conference',
      description: 'Join industry leaders for a day of talks and networking.',
      location: 'Convention Center',
      date: '2024-08-15',
      category: 'Technology',
      time: '09:00:00',
      availableSeats: 300,
      price: 200000,
      isFree: false,
    },
    {
      id: 4,
      name: 'Charity Run',
      description: 'A 5k run to raise funds for local charities.',
      location: 'City Park',
      date: '2024-08-18',
      category: 'Health & Wellness',
      time: '07:00:00',
      availableSeats: 200,
      price: 0,
      isFree: true,
    },
    {
      id: 5,
      name: 'Cooking Class',
      description: 'Learn to cook Italian cuisine with a professional chef.',
      location: 'Culinary School',
      date: '2024-08-20',
      category: 'Food & Drink',
      time: '14:00:00',
      availableSeats: 20,
      price: 150000,
      isFree: false,
    },
    {
      id: 6,
      name: 'Yoga Session',
      description: 'Morning yoga to start your day right.',
      location: 'Wellness Center',
      date: '2024-08-22',
      category: 'Health & Wellness',
      time: '06:00:00',
      availableSeats: 30,
      price: 0,
      isFree: true,
    },
    {
      id: 7,
      name: 'Book Signing',
      description: 'Meet the author and get your book signed.',
      location: 'Bookstore',
      date: '2024-08-24',
      category: 'Literature',
      time: '16:00:00',
      availableSeats: 100,
      price: 0,
      isFree: true,
    },
    {
      id: 8,
      name: 'Movie Night',
      description: 'Outdoor screening of a classic movie.',
      location: 'Community Center',
      date: '2024-08-26',
      category: 'Entertainment',
      time: '20:00:00',
      availableSeats: 75,
      price: 30000,
      isFree: false,
    },
    {
      id: 9,
      name: 'Startup Pitch',
      description: 'Watch startups pitch their ideas to investors.',
      location: 'Tech Hub',
      date: '2024-08-28',
      category: 'Business',
      time: '10:00:00',
      availableSeats: 150,
      price: 100000,
      isFree: false,
    },
    {
      id: 10,
      name: 'Music Festival',
      description: 'A full day of live music from various artists.',
      location: 'Open Field',
      date: '2024-08-30',
      category: 'Music',
      time: '12:00:00',
      availableSeats: 500,
      price: 250000,
      isFree: false,
    },
    {
      id: 11,
      name: 'Craft Fair',
      description: 'Handmade crafts from local artisans.',
      location: 'Market Square',
      date: '2024-09-02',
      category: 'Art',
      time: '09:00:00',
      availableSeats: 200,
      price: 0,
      isFree: true,
    },
    {
      id: 12,
      name: 'Dance Workshop',
      description: 'Learn to dance with professional instructors.',
      location: 'Dance Studio',
      date: '2024-09-04',
      category: 'Dance',
      time: '17:00:00',
      availableSeats: 50,
      price: 75000,
      isFree: false,
    },
    {
      id: 13,
      name: 'Science Fair',
      description: 'Discover science projects from students.',
      location: 'High School',
      date: '2024-09-06',
      category: 'Education',
      time: '10:00:00',
      availableSeats: 100,
      price: 0,
      isFree: true,
    },
    {
      id: 14,
      name: 'Wine Tasting',
      description: 'Sample a selection of fine wines.',
      location: 'Vineyard',
      date: '2024-09-08',
      category: 'Food & Drink',
      time: '14:00:00',
      availableSeats: 30,
      price: 200000,
      isFree: false,
    },
    {
      id: 15,
      name: 'Photography Walk',
      description: 'A guided walk to capture beautiful photos.',
      location: 'Downtown',
      date: '2024-09-10',
      category: 'Photography',
      time: '08:00:00',
      availableSeats: 25,
      price: 0,
      isFree: true,
    },
    {
      id: 16,
      name: 'Theater Play',
      description: 'A local production of a classic play.',
      location: 'Theater',
      date: '2024-09-12',
      category: 'Theater',
      time: '19:00:00',
      availableSeats: 150,
      price: 120000,
      isFree: false,
    },
  ];
  